component_depth: 6
languages:
  - name: javascript
    production:
      include:
        - /src
      exclude:
        - /Gruntfile.js
        - /karma.conf.js
        - /test/.*
    test:
      include:
        - /test/.*