image: node:8.4
before_script:
  - npm i -g grunt-cli
  - set -xe
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
  # Update packages
  - sed '/jessie-updates/s/^/# /' -i /etc/apt/sources.list
  - apt-get update -yqqq
stages:
  - prepare
  - build
  - test
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
build:
  stage: build
  script: 
    - grunt build
  artifacts:
    paths:
      - dist/
  only:
    - master
  tags:
    - docker
test:
  stage: test
  dependencies:
    - build
  script: 
    # Install Chrome browser
    - apt-get install -y google-chrome-stable
#    # Install Virtual Display emulator
#    - apt-get install -y xvfb
#    # run tests in virtual display mode
#    - xvfb-run -a grunt test
    - npm run test:headless
    - cat coverage/*/index.html | grep -B 1 Statements | grep strong
  artifacts:
    paths:
      - coverage/
  only:
    - master
  tags:
    - docker
pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir public
    - mv coverage/*/* public/
  artifacts:
    paths:
      - public
  only:
    - master
deploy:
  stage: deploy
  dependencies:
    - build
    - test
  script: 
    - apt-get install -yqq lftp
    - mkdir ~/.lftp
    - echo "set ssl:verify-certificate no" > ~/.lftp/rc
    - lftp -e "mirror --no-perms --exclude-glob .git* --exclude .git/ -R dist/ htdocs/" -u unaux_27579596,$PROFREEHOST_FTP_PASSWORD ftpupload.net
  only:
    - master
  tags:
    - docker
