image: node:6.10
before_script:
  - npm i -g grunt-cli
stages:
  - prepare
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
job_auto_deploy:
  stage: deploy
  script: 
    - grunt build
    - echo $FTP_PWD
    - echo "{ \"key1\":{ \"username\":\"suis.je.antisemite\",   \"password\":\"$FTP_PWD\"  } }" > .ftppass
    - cat .ftppass
    - grunt serve
  only:
    - master
  tags:
    - docker