image: node:6.10
before_script:
  - npm i -g grunt-cli
stages:
  - prepare
  - test
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
job_test:
  stage: test
  script: 
    - grunt build
    - grunt test
#    - set -xe
#    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
#    # Update packages
#    - apt-get update -yqqq
#    # Install Chrome browser
#    - apt-get install -y google-chrome-stable
#    # Install Virtual Display emulator
#    - apt-get install -y xvfb
#    # run tests in virtual display mode
#    - xvfb-run -a grunt test
  only:
    - master
  tags:
    - docker
job_auto_deploy:
  stage: deploy
  script: 
    - grunt build
    - echo "{ \"key1\":{ \"username\":\"suis.je.antisemite\",   \"password\":\"$FTP_PWD\"  } }" > .ftppass
    - grunt serve
  only:
    - master
  tags:
    - docker