image: node:6.10
before_script:
  - npm i -g npm@3.10.10
  - npm install -g grunt-cli
stages:
  - prepare
  - build
  - deploy
cache:
  paths:
    - node_modules/
install_dependencies:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
job1:
  stage: build
  script:
    - grunt build
  only:
    - master
  tags:
    - docker
job2:
  stage: deploy
  script: 
    - grunt serve
  only:
    - master
  tags:
    - docker