image: node:6.10
before_script:
  - npm i -g npm@3.10.10
  - npm i -g npmlog
  - npm install
  - npm install -g grunt-cli
stages:
  - build
  - deploy
job1:
  stage: build
  script:
    - grunt build
  only:
    - master
  tags:
    - docker
job2:
  stage: deploy
  script: 
    - grunt serve
  only:
    - master
  tags:
    - docker